DOCKER_STACKS="docker16"
NODEJS_STACKS="nodejs"
PHP_STACKS="php55 php56"
PYTHON_STACKS="python27 python34"
RUBY_STACKS="ruby19 ruby20 ruby20-puma ruby21 ruby21-puma ruby22 ruby22-puma"

export SOLUTION_STACKS="$DOCKER_STACKS $NODEJS_STACKS $PHP_STACKS $PYTHON_STACKS $RUBY_STACKS"
